comunas_interes <- c("LA FLORIDA", "PUENTE ALTO", "SANTIAGO", "ÑUÑOA", "MAIPU", "SAN MIGUEL",
                     "PROVIDENCIA", "LAS CONDES", "LA PINTANA", "VIÑA DEL MAR",
                     "RECOLETA", "LO PRADO", "MACUL", "VITACURA", "LA CISTERNA", "EL BOSQUE",
                     "INDEPENDENCIA", "ESTACION CENTRAL", "PEÑALOLEN","VALPARAISO", 
                     "CONCEPCION", "LA SERENA", "TEMUCO", "RANCAGUA", "IQUIQUE", "TALCA", "VALDIVIA", "PUERTO MONTT", "PUNTA ARENAS", "ANTOFAGASTA", 
                     "RENCA"
)


comunas_rm <- c("LA FLORIDA", "PUENTE ALTO", "SANTIAGO", "ÑUÑOA", "MAIPU", "SAN MIGUEL",
                "PROVIDENCIA", "LAS CONDES", "LA PINTANA", "PIRQUE", "SAN JOSE DE MAIPO", "COLINA", "SAN BERNARDO", "BUIN", "TALAGANTE", "PEÑAFLOR",  
                "CERRILLOS", 
                "CERRO NAVIA", 
                "CONCHALI", 
                "EL BOSQUE", 
                "ESTACION CENTRAL", 
                "HUECHURABA", 
                "INDEPENDENCIA", 
                "LA CISTERNA", 
                "LA FLORIDA", 
                "LA GRANJA", 
                "LA PINTANA", 
                "LA REINA", 
                "LAS CONDES", 
                "LO BARNECHEA", 
                "LO ESPEJO", 
                "LO PRADO", 
                "MACUL", 
                "MAIPU", 
                "ÑUÑOA", 
                "PEDRO AGUIRRE CERDA", 
                "PEÑALOLEN", 
                "PROVIDENCIA", 
                "PUDAHUEL",
                "QUILICURA",
                "QUINTA NORMAL",
                "RECOLETA",
                "RENCA",
                "SAN JOAQUIN",
                "SAN MIGUEL",
                "SAN RAMON",
                "SANTIAGO",
                "VITACURA", "MELIPILLA",
                "RECOLETA", "LO PRADO", "MACUL", "VITACURA", "LA CISTERNA", "EL BOSQUE",
                "INDEPENDENCIA", "ESTACION CENTRAL", "PEÑALOLEN",
                "RENCA"
)