comunas_interes <- c("LA FLORIDA", "PUENTE ALTO", "SANTIAGO", "ÑUÑOA", "MAIPU", "SAN MIGUEL",
                     "PROVIDENCIA", "LAS CONDES", "LA PINTANA", "VIÑA DEL MAR",
                     "RECOLETA", "LO PRADO", "MACUL", "VITACURA", "LA CISTERNA", "EL BOSQUE",
                     "INDEPENDENCIA", "ESTACION CENTRAL", "PEÑALOLEN","VALPARAISO", 
                     "CONCEPCION", "LA SERENA", "TEMUCO", "RANCAGUA", "IQUIQUE", "TALCA", "VALDIVIA", "PUERTO MONTT", "PUNTA ARENAS", "ANTOFAGASTA", 
                     "RENCA"
)


comunas_rm <- c("ALHUE", "BUIN", "CALERA DE TANGO", 
                "CERRILLOS", "CERRO NAVIA", "COLINA", "CONCHALI", "CURACAVI", 
                "EL BOSQUE", "EL MONTE", "ESTACION CENTRAL", "HUECHURABA", "INDEPENDENCIA", 
                "ISLA DE MAIPO", "LA CISTERNA", "LA FLORIDA", "LA GRANJA", "LA PINTANA", 
                "LA REINA", "LAMPA", "LAS CONDES", "LO BARNECHEA", "LO ESPEJO", 
                "LO PRADO", "MACUL", "MAIPU", "MARIA PINTO", "MELIPILLA", "ÑUÑOA", 
                "PADRE HURTADO", "PAINE", "PEDRO AGUIRRE CERDA", "PEÑAFLOR", 
                "PEÑALOLEN", "PIRQUE", "PROVIDENCIA", "PUDAHUEL", "PUENTE ALTO", 
                "QUILICURA", "QUINTA NORMAL", "RECOLETA", "RENCA", "SAN BERNARDO", 
                "SAN JOAQUIN", "SAN JOSE DE MAIPO", "SAN MIGUEL", "SAN PEDRO", 
                "SAN RAMON", "SANTIAGO", "TALAGANTE", "TILTIL", "VITACURA")